[#81] AuthApi 수정
mimi-teams/w2m-backend pull request #84
Opened 2023-01-07 14:48 UTC by YeongRoYun

# 🙊 Issues

#81
# 🤠 작업 내용

- 테스트를 위해 Oauth 로그인 API 변경
- 백엔드에서도 Jwt Token 을 발급받을 수 있도록 만들었다.

2023-01-11 04:20 UTC, Yeh35 requested changes

2023-01-11 04:20 UTC, Yeh35 commented on src/main/java/com/mimi/w2m/backend/converter/db/OAuth2PlatformTypeConverter.java
> +}
Enum은 직접 컴버터를 만드는 대신 `@enumerated(enumtype.string)`를 사용하는게 좋아.

2023-01-11 09:55 UTC, YeongRoYun commented on src/main/java/com/mimi/w2m/backend/converter/db/OAuth2PlatformTypeConverter.java
> +}
고마웡 ㅜㅜㅜ

2023-01-12 14:25 UTC, YeongRoYun commented on src/main/java/com/mimi/w2m/backend/api/v1/EventApi.java
> +
다해땅

2023-01-12 14:25 UTC, YeongRoYun commented on src/main/java/com/mimi/w2m/backend/client/kakao/api/KaKaoApiClient.java
> +    @Retryable(backoff = @Backoff(delay = 50, multiplier = 2, maxDelay = 1000), value = BadGatewayException.class)
ㅎㅎ

2023-01-13 02:21 UTC, Yeh35 approved these changes
고생했엉

2023-01-13 02:23 UTC, merged